# This is a basic workflow to help you get started with Actions

name: CLion

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run download
        run: wget -v https://download.jetbrains.com/cpp/CLion-241.14494.154.exe?_gl=1*nn8xy0*_ga*NjU2Mjg5MTAwLjE3MDg3NzA5NTA.*_ga_9J976DJZ68*MTcxMTExMTQ4NC45LjEuMTcxMTExMTUxOS4yNS4wLjA.

      # Runs a set of commands using the runners shell
      - name: Commit
        run: |
          git add *
          git commit -m "download clion"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
